POST http://localhost:31337/offers/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFib2JhMTJAbWFpbC5ydSIsImlkIjoiNjU5ZGE0ZjBmNDkzNzlhOGIyZjhmMTgzIiwiaWF0IjoxNzA0ODMwMjAyLCJleHAiOjE3MDUwMDMwMDJ9.7T0CynXo_sOUxFAbCznhSRmjsC4Zr_pieNwG4j-teEc

{
  "title": "asdgadsgfds",
  "description": "Сдаетсяdfsd небольшой дом",
  "postDate": "2023-07-09T19:00:00.000Z",
  "city": "Paris",
  "photos": [
    "1.png",
    "2.png",
    "3.png",
    "4.png",
    "5.png",
    "6.png"
  ],
  "isPremium": true,
  "housingType": "House",
  "roomsNumber": 8,
  "guestsNumber": 10,
  "rentalPrice": 100000,
  "conveniences": [
    "Breakfast",
    "AirConditioning"
  ],
  "coordinates": {
    "latitude": 48.85661,
    "longitude": 2.351499
  }
}

###

GET http://localhost:31337/offers/

###
@offerId = 659da9a85f54297bdb79469d

GET http://localhost:31337/offers/{{offerId}}

###

PUT http://localhost:31337/offers/{{offerId}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFib2JhMTJAbWFpbC5ydSIsImlkIjoiNjU5ZGE0ZjBmNDkzNzlhOGIyZjhmMTgzIiwiaWF0IjoxNzA0ODMwMjAyLCJleHAiOjE3MDUwMDMwMDJ9.7T0CynXo_sOUxFAbCznhSRmjsC4Zr_pieNwG4j-teEc

{
  "title": "Приличный дом",
  "postDate": "2023-07-09T19:00:00.000Z"
}

###

DELETE http://localhost:31337/offers/{{offerId}}
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFib2JhMTJAbWFpbC5ydSIsImlkIjoiNjU5ZGE0ZjBmNDkzNzlhOGIyZjhmMTgzIiwiaWF0IjoxNzA0ODMwMjAyLCJleHAiOjE3MDUwMDMwMDJ9.7T0CynXo_sOUxFAbCznhSRmjsC4Zr_pieNwG4j-teEc

###
@city = Paris

GET http://localhost:31337/offers/premium/{{city}}

###

GET http://localhost:31337/offers/favourites
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFib2JhMTJAbWFpbC5ydSIsImlkIjoiNjU5ZGE0ZjBmNDkzNzlhOGIyZjhmMTgzIiwiaWF0IjoxNzA0ODMwMjAyLCJleHAiOjE3MDUwMDMwMDJ9.7T0CynXo_sOUxFAbCznhSRmjsC4Zr_pieNwG4j-teEc


###

POST http://localhost:31337/offers/{{offerId}}/addFavourite
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFib2JhMTJAbWFpbC5ydSIsImlkIjoiNjU5ZGE0ZjBmNDkzNzlhOGIyZjhmMTgzIiwiaWF0IjoxNzA0ODMwMjAyLCJleHAiOjE3MDUwMDMwMDJ9.7T0CynXo_sOUxFAbCznhSRmjsC4Zr_pieNwG4j-teEc


###

DELETE http://localhost:31337/offers/{{offerId}}/deleteFavourite
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFib2JhMTJAbWFpbC5ydSIsImlkIjoiNjU5ZGE0ZjBmNDkzNzlhOGIyZjhmMTgzIiwiaWF0IjoxNzA0ODMwMjAyLCJleHAiOjE3MDUwMDMwMDJ9.7T0CynXo_sOUxFAbCznhSRmjsC4Zr_pieNwG4j-teEc

