@offerId = 659dab308395be38a10f12ef

POST http://localhost:31337/comments/{{offerId}}/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFib2JhMTIzQG1haWwucnUiLCJpZCI6IjY1OWRhYTYwODM5NWJlMzhhMTBmMTI5ZSIsImlhdCI6MTcwNDgzMTU5MiwiZXhwIjoxNzA1MDA0MzkyfQ.p4LK0E1r4tHhWtlp9B0DIJkop-AhnEdr5r9TXFffs90

{
  "text": "Не понравилось",

  "postDate": "2023-07-09T19:00:00.000Z",

  "rating": 3,

  "offerId": "659dab308395be38a10f12ef"
}

###

GET http://localhost:31337/comments/{{offerId}}/
