@offerId = 659da2c072b3d567fe3f7f7b

POST http://localhost:31337/comments/{{offerId}}/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFib2JhQG1haWwucnUiLCJpZCI6IjY1OWQ3ZmE2NGFmZjM2NWFmOWJiNzExNiIsImlhdCI6MTcwNDgyMDY1NCwiZXhwIjoxNzA0OTkzNDU0fQ.pk5d3xC8UjrZ4XMfxN7U1FT_TKTmTrh7E4jhqBPq6aE

{
  "text": "Не понравилось",

  "postDate": "2023-07-09T19:00:00.000Z",

  "rating": 3,

  "offerId": "659da2c072b3d567fe3f7f7b"
}

###

GET http://localhost:31337/comments/{{offerId}}/
